namespace: devops-app

backend:
  image: asimkhankhitran/devops-backend
  tag: latest
  replicas: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

frontend:
  image: asimkhankhitran/devops-frontend
  tag: latest
  replicas: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"

redis:
  image: redis
  tag: 7-alpine
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

config:
  redisHost: redis
  redisPort: 6379

secret:
  secretKey: change-this-in-production

ingress:
  enabled: true
  className: nginx
  rateLimit: 100
